# Generated by Django 4.0.4 on 2025-07-14
# Data migration to populate existing assignments with monitoring forms

from django.db import migrations


def populate_monitoring_forms(apps, schema_editor):
    """
    For existing MobileAssignments, add all published monitoring forms
    (children) for each assigned registration form.

    This ensures backward compatibility after the selective monitoring
    form assignment feature, where monitoring forms are no longer
    auto-included during sync.
    """
    MobileAssignment = apps.get_model('v1_mobile', 'MobileAssignment')
    Forms = apps.get_model('v1_forms', 'Forms')

    # FormStatus.published = 2
    PUBLISHED_STATUS = 2

    for assignment in MobileAssignment.objects.all():
        # Get all registration forms (parent=null) in this assignment
        registration_forms = assignment.forms.filter(parent__isnull=True)

        for reg_form in registration_forms:
            # Find all published monitoring forms for this registration
            monitoring_forms = Forms.objects.filter(
                parent=reg_form,
                status=PUBLISHED_STATUS
            )
            # Add them to the assignment
            assignment.forms.add(*monitoring_forms)


def reverse_populate_monitoring_forms(apps, schema_editor):
    """
    Reverse migration: remove all monitoring forms from assignments,
    leaving only registration forms.
    """
    MobileAssignment = apps.get_model('v1_mobile', 'MobileAssignment')

    for assignment in MobileAssignment.objects.all():
        # Get all monitoring forms (parent is not null) in this assignment
        monitoring_forms = assignment.forms.filter(parent__isnull=False)
        # Remove them from the assignment
        assignment.forms.remove(*monitoring_forms)


class Migration(migrations.Migration):

    dependencies = [
        ('v1_mobile', '0003_initial'),
        ('v1_forms', '0008_forms_deleted_at'),
    ]

    operations = [
        migrations.RunPython(
            populate_monitoring_forms,
            reverse_code=reverse_populate_monitoring_forms,
        ),
    ]
