# Generated by Django 4.0.4 on 2025-07-14
# Data migration to populate existing assignments with monitoring forms

from django.db import migrations


def populate_monitoring_forms(apps, schema_editor):
    """
    For existing MobileAssignments, add all published monitoring forms
    (children) for each assigned registration form.

    This ensures backward compatibility after the selective monitoring
    form assignment feature, where monitoring forms are no longer
    auto-included during sync.
    """
    MobileAssignment = apps.get_model('v1_mobile', 'MobileAssignment')
    Forms = apps.get_model('v1_forms', 'Forms')

    # FormStatus.published = 2
    PUBLISHED_STATUS = 2

    for assignment in MobileAssignment.objects.prefetch_related('forms').all():
        # Get registration form IDs in this assignment
        # Only consider published registration forms to avoid assigning
        # monitoring forms for draft/unpublished registrations
        registration_ids = list(
            assignment.forms.filter(
                parent__isnull=True,
                status=PUBLISHED_STATUS
            ).values_list('id', flat=True)
        )

        if registration_ids:
            # Get all published monitoring forms for these registrations
            # in a single query
            monitoring_forms = Forms.objects.filter(
                parent_id__in=registration_ids,
                status=PUBLISHED_STATUS
            )
            # Add them to the assignment
            assignment.forms.add(*monitoring_forms)


def reverse_noop(apps, schema_editor):
    """
    No-op reverse migration.

    We don't remove monitoring forms on rollback because:
    1. After this migration, users may have explicitly configured
       monitoring form assignments
    2. Removing all monitoring forms would cause data loss
    3. The old behavior (auto-include) still works with explicit assignments
    """
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('v1_mobile', '0003_initial'),
        ('v1_forms', '0008_forms_deleted_at'),
    ]

    operations = [
        migrations.RunPython(
            populate_monitoring_forms,
            reverse_code=reverse_noop,
        ),
    ]
