"""
Django settings for mis project.

Generated by 'django-admin startproject' using Django 4.0.1.

For more information on this file, see
https://docs.djangoproject.com/en/4.0/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.0/ref/settings/
"""
import sys
from datetime import timedelta
from django.core.exceptions import ImproperlyConfigured
from os import environ
from pathlib import Path

APP_NAME = environ.get("APP_NAME", "mis")
APP_SHORT_NAME = environ.get("APP_SHORT_NAME", "mis")
APK_SHORT_NAME = environ.get("APK_SHORT_NAME", "mis-mobile")
APK_NAME = environ.get("APK_NAME", "MIS mobile")
SHOW_LANDING_PAGE = environ.get("SHOW_LANDING_PAGE", "false").lower() == "true"

if 'SENTRY_DSN' in environ:
    import sentry_sdk
    from sentry_sdk.integrations.django import DjangoIntegration
    sentry_environment = "production" if "PROD" in environ else "develop"
    sentry_sdk.init(
        dsn=environ['SENTRY_DSN'],
        # Set traces_sample_rate to 1.0 to capture 100%
        # of transactions for performance monitoring.
        environment=sentry_environment,
        traces_sample_rate=1.0,
        # Set profiles_sample_rate to 1.0 to profile 100%
        # of sampled transactions.
        # We recommend adjusting this value in production.
        profiles_sample_rate=1.0,
        ignore_errors=[
            "django.core.exceptions.PermissionDenied",
            "django.http.response.Http404",
            "django.http.response.HttpResponseNotFound",
            "django.http.response.HttpResponseForbidden",
            "django.http.response.HttpResponseBadRequest",
        ],
        integrations=[DjangoIntegration()]
    )

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.0/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = environ["DJANGO_SECRET"]

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True if "DEBUG" in environ else False
PROD = True if "PROD" in environ else False
# True only when running under `manage.py test`. Used to keep legacy
# test-only conveniences (the admin@akvo.org auto-create on login) out of
# production code paths, and — since this iteration — to hold host
# routing off for the suite. Matched positionally, so a stray "test"
# argument to some other command cannot switch it on. Defined up here
# because BASE_DOMAIN below now depends on it.
TESTING = sys.argv[1:2] == ["test"]

# Host-based tenant routing. Unset means single-host: every host is the
# base domain, nothing resolves to a tenant, and the routing is inert —
# which is how the test suite and any non-SaaS deployment run.
#
# Forced off under `test` whatever the environment says. The Django test
# client's host is "testserver", which is nobody's base domain, so a
# BASE_DOMAIN inherited from a developer's .env would 404 the entire
# suite. The tests that exercise host routing opt back in with
# override_settings, which is how they read anyway.
BASE_DOMAIN = "" if TESTING else environ.get("BASE_DOMAIN", "")

# Whether this deployment offers self-service sign-up. The default
# follows BASE_DOMAIN, which is what distinguishes the multi-tenant
# SaaS from a dedicated single-customer deployment: mohhs-mis and
# unicef-fsm run with BASE_DOMAIN unset, have no sign-up page, and
# should not quietly accept a POST to /register.
#
# Forced on under `manage.py test`, because BASE_DOMAIN is forced empty
# there (above) and the default would otherwise turn every existing
# registration test into a 403. The gate's own tests set it explicitly.
#
# Local development also runs with BASE_DOMAIN unset, so working on the
# sign-up form means setting SIGNUP_ENABLED=true in .env. That is in
# env.example, which is the file a developer already copies -- without
# it, the form renders and the endpoint refuses it, which is a
# confusing afternoon.
_SIGNUP_ENABLED = environ.get("SIGNUP_ENABLED", "").strip().lower()
if TESTING:
    SIGNUP_ENABLED = True
elif _SIGNUP_ENABLED in ("true", "false"):
    SIGNUP_ENABLED = _SIGNUP_ENABLED == "true"
else:
    SIGNUP_ENABLED = bool(BASE_DOMAIN)

# The label the platform console answers on, under BASE_DOMAIN -- see
# env.example and doc/notes/platform-console.md. Normalised here and
# nowhere else: "" would put the console at ".<BASE_DOMAIN>", which no
# browser sends, so empty means the default rather than the apex.
ADMIN_SUBDOMAIN = environ.get("ADMIN_SUBDOMAIN", "admin") or "admin"

# Origin that serves embedded dashboards' author markup, e.g.
# "https://embed.example.com". It MUST NOT be this application's origin:
# the whole point is that a pasted snippet runs somewhere its scripts
# cannot reach our DOM or the AUTH_TOKEN cookie (which is host-only, and
# readable from JavaScript). Unset means embedding is not configured for
# this deployment, and the viewer says so rather than falling back to
# serving the markup here -- that fallback would be the cross-site
# scripting hole the separate origin exists to prevent.
EMBED_HOST = environ.get("EMBED_HOST", "")


ALLOWED_HOSTS = ["*"]

# Application definition

# Default django apps
DJANGO_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
]

# Add third party apps below
EXTERNAL_APPS = [
    "rest_framework",
    "rest_framework_simplejwt",
    "drf_spectacular",
    "django_dbml",
    "django_extensions",
    "django_q",
]

# Add API apps below
API_APPS = [
    "api.v1.v1_users",
    "api.v1.v1_profile",
    "api.v1.v1_forms",
    "api.v1.v1_data",
    "api.v1.v1_approval",
    "api.v1.v1_jobs",
    "api.v1.v1_mobile",
    "api.v1.v1_files",
    "api.v1.v1_visualization",
    "api.v1.v1_chatbot",
    "api.sentry_test",
]

# When two apps define a management command of the same name the one
# listed first here wins, so api.v1.v1_users precedes django.contrib.auth:
# its `createsuperuser` is the one that understands --tenant, and without
# this ordering the seeded superadmin lands in the tenant-less space.
INSTALLED_APPS = (
    ["api.v1.v1_users"]
    + DJANGO_APPS
    + [app for app in API_APPS if app != "api.v1.v1_users"]
    + EXTERNAL_APPS
)

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "middleware.tenant.TenantMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "middleware.user_activity.UserActivity",
]

ROOT_URLCONF = "mis.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [Path.joinpath(BASE_DIR, "mis/templates")],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.debug",
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "mis.wsgi.application"

# How many proxies sit between a client and this process. DRF's
# throttles use it to find the client address in X-Forwarded-For, and
# they count from the right-hand end -- `addrs[-NUM_PROXIES]` -- which
# is the only safe reading. The GCLB preserves whatever the caller sent
# and appends to it, so the leftmost entries are attacker-controlled
# and the rightmost ones are not. Nothing in this codebase should parse
# the header by hand; DRF's `BaseThrottle.get_ident` is the one reader,
# and `RegisterSerializer` uses it too so the captcha and the throttles
# cannot disagree about who the caller is.
#
# 0, the default, means "use REMOTE_ADDR", which is correct wherever
# nothing trustworthy sets the header: local development, the test
# suite, and every single-host deployment. Leaving the setting out
# entirely is NOT equivalent -- DRF then keys on the whole header,
# attacker-supplied prefix included. A non-zero default is worse:
# DRF clamps the index with min(NUM_PROXIES, len(addrs)), so where
# there is no proxy a one-entry header resolves to the entry the client
# sent, which is the key rotation this is meant to deny.
#
# The deployed value is 2, from the k8s secret: the GCLB appends both
# the client address and its own, giving
# "[<client-supplied>, ]<client-ip>, <GFE-ip>", and nginx passes the
# header through without appending, so the client sits second from the
# right.
NUM_PROXIES = int(environ.get("NUM_PROXIES") or 0)

# Rates for the throttles in utils/throttling.py. Literals rather than
# env overrides: retuning one is a one-line pull request, which is
# reviewable, and a variable nobody sets would only hide where the real
# value came from.
#
# `login_ip` is deliberately loose. A whole office arrives from one NAT
# address, so a tight per-IP login limit locks out a customer; the
# tight limit there is per-email. `email_dispatch_email` is
# deliberately not lower than 3: a tight per-email limit on
# forgot-password is itself an attack, because anyone who knows an
# address could then deny its owner password recovery.
THROTTLE_RATES = {
    "email_dispatch_ip": "10/hour",
    "email_dispatch_email": "3/hour",
    "login_ip": "60/hour",
    "login_email": "10/hour",
}
# Inert under `manage.py test`. Every Django test request arrives from
# 127.0.0.1 and the cache is process-wide, so live rates would make
# unrelated endpoint tests fail by call count and by shuffle order. A
# rate of None makes SimpleRateThrottle.allow_request return True
# before it touches the cache. The throttle tests patch `rate` on the
# class instead -- see utils/throttling.py for why override_settings
# cannot reach it.
if TESTING:
    THROTTLE_RATES = {scope: None for scope in THROTTLE_RATES}

# Rest Settings
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        # Subclasses the mobile one, which it replaces rather than joins:
        # inspection has to be recognised everywhere, and a second entry
        # would only mean whichever ran first decided.
        "api.v1.v1_users.authentication."
        "InspectionAwareJWTAuthentication",
    ),
    "DEFAULT_VERSIONING_CLASS": "rest_framework.versioning.URLPathVersioning",
    "DATE_FORMAT": "%d-%m-%Y",
    "DEFAULT_VERSION": "v1",
    "DATETIME_FORMAT": "%d-%m-%Y %H:%M:%S",
    "DEFAULT_SCHEMA_CLASS": "drf_spectacular.openapi.AutoSchema",
    "DEFAULT_PAGINATION_CLASS":
    "rest_framework.pagination.LimitOffsetPagination",
    "PAGE_SIZE": 10,
    "NUM_PROXIES": NUM_PROXIES,
    "DEFAULT_THROTTLE_RATES": THROTTLE_RATES,
}
SPECTACULAR_SETTINGS = {
    "TITLE": APP_NAME,
    "DESCRIPTION": "",
    "VERSION": "1.0.0",
    "SORT_OPERATIONS": False,
    "COMPONENT_SPLIT_REQUEST": True,
}
# JWT Config
SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(hours=12),
    "REFRESH_TOKEN_LIFETIME": timedelta(days=10),
    "AUTH_TOKEN_CLASSES": (
        "rest_framework_simplejwt.tokens.AccessToken",
        "api.v1.v1_mobile.authentication.MobileAssignmentToken",
        "api.v1.v1_users.authentication.TenantInspectionToken",
    ),
}
# Database
# https://docs.djangoproject.com/en/4.0/ref/settings/#databases
DATABASES = {
    "default": {
        "ENGINE": "django.db.backends.postgresql",
        "NAME": environ["DB_SCHEMA"],
        "USER": environ["DB_USER"],
        "PASSWORD": environ["DB_PASSWORD"],
        "HOST": environ["DB_HOST"],
        "PORT": "5432",
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.0/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation"
        ".UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation"
        ".NumericPasswordValidator",
    },
]

# Internationalization
# https://docs.djangoproject.com/en/4.0/topics/i18n/

LANGUAGE_CODE = "en-us"

"""
The TIME_ZONE has been set to 'Pacific/Fiji'
to align with the application's focus on Fiji.
"""
TIME_ZONE = "Pacific/Fiji"

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.0/howto/static-files/

STATIC_URL = "static-files/"

# For Caching API call
CACHES = {
    "default": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/cache",
    },
    # Embed previews live here rather than in `default`, which
    # v1_forms.signals clears wholesale on any form change. Sharing it
    # would mean an author's preview dying because somebody else edited a
    # form — and, under `manage.py test --parallel`, another process's
    # form seeding racing a preview to 404. The default cache's own
    # comment asks unrelated callers to do exactly this.
    "embed": {
        "BACKEND": "django.core.cache.backends.filebased.FileBasedCache",
        "LOCATION": "/var/tmp/cache-embed",
    },
    # Throttle counters, in a third alias rather than a corner of
    # `default`, because v1_forms.signals clears `default` wholesale on
    # any form change: a budget that resets whenever somebody edits a
    # form is not a budget. Same reasoning as `embed` above, which asks
    # unrelated callers to do exactly this.
    #
    # LocMemCache under `manage.py test`. A file-based cache shared
    # between `--parallel` workers is the cross-process race `embed`
    # describes, and throttle counters are far more sensitive to it:
    # one worker spending another's budget fails tests by shuffle
    # order. LocMemCache is per-process, which is the isolation a
    # throttle test wants anyway.
    "throttle": {
        "BACKEND": (
            "django.core.cache.backends.locmem.LocMemCache"
            if TESTING
            else "django.core.cache.backends.filebased.FileBasedCache"
        ),
        "LOCATION": "/var/tmp/cache-throttle",
    },
}
CACHE_FOLDER = "/tmp/cache/"

# Default primary key field type
# https://docs.djangoproject.com/en/4.0/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"

AUTH_USER_MODEL = "v1_users.SystemUser"

AUTHENTICATION_BACKENDS = [
    "utils.tenant_auth_backend.TenantAwareBackend",
]

# MOBILE ENV VARIABLES
WEBDOMAIN = environ.get("WEBDOMAIN", "http://localhost:3000")
APK_UPLOAD_SECRET = environ.get("APK_UPLOAD_SECRET")
MASTER_DATA = "./source"
STORAGE_PATH = environ.get("STORAGE_PATH", "./storage")

# AI CHATBOT ENV VARIABLES
OPENAI_API_KEY = environ.get("OPENAI_API_KEY", "")
OPENAI_ASSISTANT_ID = environ.get("OPENAI_ASSISTANT_ID", "")
OPENAI_VECTOR_STORE_ID = environ.get("OPENAI_VECTOR_STORE_ID", "")

FORM_GEO_VALUE = {"lat": -18.1236015, "lng": 178.3805867}  # Fiji coordinates
FORM_IMPORT_MAX_FILE_SIZE = int(
    environ.get("FORM_IMPORT_MAX_FILE_SIZE", 5 * 1024 * 1024)
)

# How long a workspace has to finish /register/configure before it is
# purged (see api/v1/v1_users/tasks.py). This is also the activation
# link's lifetime: a link that outlived the workspace it activates
# would verify an account whose tenant had already been deleted, so
# the two numbers are one setting rather than two that can disagree.
TENANT_PURGE_AFTER_HOURS = int(
    environ.get("TENANT_PURGE_AFTER_HOURS") or 48
)
# Refused at boot rather than defended against at every read: zero or
# less would purge a workspace registered a second ago and expire every
# activation link as it was issued.
if TENANT_PURGE_AFTER_HOURS < 1:
    raise ImproperlyConfigured(
        "TENANT_PURGE_AFTER_HOURS must be at least 1; got {0}.".format(
            TENANT_PURGE_AFTER_HOURS
        )
    )

BUCKET_NAME = "mis"
FAKE_STORAGE = False

# SMTP everywhere, through Django's own backend. The Mailjet REST backend
# this replaces was an unmaintained third-party package that reported a
# message as sent whether or not the provider had taken it, and exposed no
# timeout, so a hung provider could hold a gunicorn worker open forever.
#
# The defaults point at the local Mailpit container, which accepts anything
# and shows it in a web inbox. Registration is why that matters: the
# activation link is the only way to finish signing up, so a developer with
# no mail account could not otherwise exercise the flow at all. A deployment
# that forgets to set EMAIL_HOST therefore fails to resolve "mailpit" and
# logs the error rather than sending real mail somewhere unintended.
EMAIL_BACKEND = environ.get(
    "EMAIL_BACKEND", "django.core.mail.backends.smtp.EmailBackend"
)
EMAIL_HOST = environ.get("EMAIL_HOST", "mailpit")
EMAIL_PORT = int(environ.get("EMAIL_PORT") or 1025)
EMAIL_HOST_USER = environ.get("EMAIL_HOST_USER", "")
EMAIL_HOST_PASSWORD = environ.get("EMAIL_HOST_PASSWORD", "")


def _flag(name):
    """Read a boolean env var, treating unset and empty as False.

    Written out rather than inlined because getting it wrong is silent:
    bool("false") is True, which would turn implicit SSL on for Mailpit
    and hang every local send.
    """
    return environ.get(name, "").strip().lower() in ("1", "true", "yes")


# Mutually exclusive, and Django raises if both are set. Implicit SSL from
# the first byte is port 465; STARTTLS on an initially plaintext connection
# is 587. Mailpit wants neither, which is why both default to off.
EMAIL_USE_SSL = _flag("EMAIL_USE_SSL")
EMAIL_USE_TLS = _flag("EMAIL_USE_TLS")
# Seconds. Without it a hung server holds the sending thread indefinitely,
# and eight of the seventeen send sites run inside request handling against
# six gunicorn workers.
EMAIL_TIMEOUT = int(environ.get("EMAIL_TIMEOUT") or 10)
EMAIL_FROM = environ.get("EMAIL_FROM", "noreply@akvo.org")

COUNTRY_NAME = "fiji"

TEST_ENV = False

Q_CLUSTER = {
    "name": "DjangORM",
    "workers": 4,
    "timeout": 600,
    "retry": 1200,
    "queue_limit": 50,
    "bulk": 10,
    "orm": "default",
}

# Application logs go to stderr, which is where a container's log collector
# reads from. What was here before was the framework's placeholder: a file
# handler wired to a logger literally named "your_app_name", so no logger in
# this codebase had a handler and nothing it logged was ever written down.
#
# The handler is attached to the root logger rather than to named ones so
# that every module's getLogger(__name__) is covered without a registry to
# keep in step. Django's own console handler is gated behind
# require_debug_true and so is silent in production; this one is not.
LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "formatters": {
        "standard": {
            "format": "%(asctime)s %(levelname)s %(name)s %(message)s",
        },
    },
    "handlers": {
        "console": {
            "class": "logging.StreamHandler",
            "formatter": "standard",
        },
    },
    "root": {
        "handlers": ["console"],
        "level": environ.get("LOG_LEVEL", "INFO"),
    },
}
