# Generated by Django 4.0.4 on 2026-06-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0005_add_administration_path_index'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolefeatureaccess',
            name='access',
            field=models.IntegerField(choices=[(1, 'Invite User'), (2, 'Form Builder')]),
        ),
        migrations.AlterField(
            model_name='rolefeatureaccess',
            name='type',
            field=models.IntegerField(choices=[(1, 'User Access'), (2, 'Form Builder')]),
        ),
    ]
