# Generated by Django 4.0.4 on 2026-07-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0003_organisation_tenant_alter_organisation_name_and_more'),
        ('v1_profile', '0006_alter_rolefeatureaccess_access_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='administration',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administrations', to='v1_users.tenant'),
        ),
        migrations.AddField(
            model_name='administrationattribute',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='administration_attributes', to='v1_users.tenant'),
        ),
        migrations.AddField(
            model_name='entity',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='entities', to='v1_users.tenant'),
        ),
        migrations.AddField(
            model_name='levels',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='levels', to='v1_users.tenant'),
        ),
        migrations.AddConstraint(
            model_name='administration',
            constraint=models.UniqueConstraint(condition=models.Q(('parent__isnull', True)), fields=('tenant',), name='unique_root_administration_per_tenant'),
        ),
        migrations.AddConstraint(
            model_name='levels',
            constraint=models.UniqueConstraint(fields=('tenant', 'level'), name='unique_level_per_tenant'),
        ),
    ]
