# Generated by Django 4.0.4 on 2026-07-31 09:21

from django.db import migrations, models
import django.db.models.deletion


def stamp_roles_from_their_level(apps, schema_editor):
    """Fill the new column from where ownership already lived.

    Run before the unique constraint is added: leaving every row NULL would
    make each existing role look like it belongs to the same (tenant-less)
    workspace, and two legacy roles sharing a name would then collide.
    """
    Role = apps.get_model("v1_profile", "Role")
    Levels = apps.get_model("v1_profile", "Levels")
    # A subquery rather than F("administration_level__tenant"): an UPDATE
    # cannot follow a join.
    Role.objects.update(
        tenant_id=models.Subquery(
            Levels.objects.filter(
                pk=models.OuterRef("administration_level_id")
            ).values("tenant_id")[:1]
        )
    )


def unstamp(apps, schema_editor):
    apps.get_model("v1_profile", "Role").objects.update(tenant=None)


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0005_systemuser_is_active'),
        ('v1_profile', '0007_administration_tenant_administrationattribute_tenant_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='roles', to='v1_users.tenant'),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.RunPython(
            stamp_roles_from_their_level, unstamp, elidable=True
        ),
        migrations.AddConstraint(
            model_name='role',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_role_name_per_tenant'),
        ),
    ]
