# Generated by Django 4.0.4 on 2026-08-20 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_profile', '0008_role_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolefeatureaccess',
            name='access',
            field=models.IntegerField(choices=[(1, 'Invite User'), (3, 'Form View'), (4, 'Form Create'), (5, 'Form Edit'), (6, 'Form Publish'), (7, 'Form Delete'), (8, 'Dashboard View'), (9, 'Dashboard Create'), (10, 'Dashboard Edit'), (11, 'Dashboard Publish'), (12, 'Dashboard Delete')]),
        ),
        migrations.AlterField(
            model_name='rolefeatureaccess',
            name='type',
            field=models.IntegerField(choices=[(1, 'User Access'), (2, 'Form Builder'), (3, 'Dashboard Builder')]),
        ),
    ]
