---
version: "3.9"
services:
  mainnetwork:
    ports:
      - 8081:8081
      - 19000:19000
  mobileapp:
    image: akvo/akvo-node-18-alpine:20250306.055839.23cadbd
    command: ["./start.sh"]
    volumes:
      - akvo-mis-docker-mobile-sync:/app/node_modules:nocopy
      - ./app:/app:delegated
      - ./.git:/app/.git:ro
    working_dir: /app
    environment:
      - APP_NAME=${APP_NAME}
      - APP_SHORT_NAME=${APP_SHORT_NAME}
      - BACKEND_IP_ADDRESS=${IP_ADDRESS}
      - EXPO_TOKEN
      - SENTRY_ENV=${SENTRY_MOBILE_ENV}
      - SENTRY_DSN=${SENTRY_MOBILE_DSN}
      - SENTRY_AUTH_TOKEN=${SENTRY_MOBILE_AUTH_TOKEN}
    network_mode: service:mainnetwork
volumes:
  akvo-mis-docker-mobile-sync:
    external: true
