# Generated by Django 4.0.4 on 2026-06-02 01:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0006_alter_questions_dependency_rule'),
    ]

    operations = [
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.IntegerField(choices=[(1, 'Geo'), (2, 'Administration'), (3, 'Text'), (4, 'Number'), (5, 'Option'), (6, 'Multiple_Option'), (7, 'Cascade'), (8, 'Image'), (9, 'Date'), (10, 'Autofield'), (11, 'Attachment'), (12, 'Signature'), (13, 'Input')]),
        ),
    ]
