# Generated by Django 4.0.4 on 2026-06-09 01:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_forms', '0006_alter_questions_dependency_rule'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPublishedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('schema', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'db_table': 'form_published_version',
                'ordering': ['form', 'version'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='questiongroup',
            name='unique_form_question_group',
        ),
        migrations.RemoveConstraint(
            model_name='questions',
            name='unique_form_question',
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='forms',
            name='created',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='created_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forms',
            name='default_language',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='description',
            field=models.TextField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='languages',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='forms',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'published')], default=1),
        ),
        migrations.AddField(
            model_name='forms',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='updated',
            field=models.DateTimeField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='updated_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forms_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questionoptions',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='addon_after',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='addon_before',
            field=models.CharField(default=None, max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='center',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='data_api_url',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='disabled',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='hidden_string',
            field=models.BooleanField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='required_double_entry',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='questions',
            name='translations',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='variable_name',
            field=models.CharField(default=None, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='tree_option',
            field=models.CharField(default=None, max_length=191, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='limit',
            field=models.IntegerField(default=None, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='columns',
            field=models.JSONField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.IntegerField(choices=[(1, 'Geo'), (3, 'Text'), (4, 'Number'), (5, 'Option'), (6, 'Multiple_Option'), (7, 'Cascade'), (8, 'Image'), (9, 'Date'), (10, 'Autofield'), (11, 'Attachment'), (12, 'Signature'), (13, 'Input'), (14, 'Geoshape'), (15, 'Geotrace'), (16, 'Tree'), (17, 'Table')]),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('form', 'name'), name='unique_active_form_question_group'),
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('form', 'name'), name='unique_active_form_question'),
        ),
        migrations.AddField(
            model_name='formpublishedversion',
            name='form',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_versions', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='formpublishedversion',
            name='published_by',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_form_versions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='forms',
            name='active_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_forms', to='v1_forms.formpublishedversion'),
        ),
        migrations.AlterUniqueTogether(
            name='formpublishedversion',
            unique_together={('form', 'version')},
        ),
    ]
