# Generated by Django 4.0.4 on 2026-06-02 08:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0006_alter_questions_dependency_rule'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='forms',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'published')], default=2),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='questions',
            name='type',
            field=models.IntegerField(choices=[(1, 'Geo'), (2, 'Administration'), (3, 'Text'), (4, 'Number'), (5, 'Option'), (6, 'Multiple_Option'), (7, 'Cascade'), (8, 'Image'), (9, 'Date'), (10, 'Autofield'), (11, 'Attachment'), (12, 'Signature'), (13, 'Input')]),
        ),
    ]
