# Generated by Django 4.0.4 on 2026-06-09 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0007_formpublishedversion_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
