# Generated by Django 4.0.4 on 2026-06-02 02:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0007_alter_questions_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='previous_version',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='next_versions', to='v1_forms.forms'),
        ),
        migrations.AddField(
            model_name='forms',
            name='published_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AddField(
            model_name='forms',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'published')], default=2),
            preserve_default=False,
        ),
    ]
