# Generated by Django 4.0.4 on 2026-06-03 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0007_forms_previous_version_forms_published_at_and_more'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='questiongroup',
            name='unique_form_question_group',
        ),
        migrations.RemoveConstraint(
            model_name='questions',
            name='unique_form_question',
        ),
        migrations.AlterUniqueTogether(
            name='questiongroup',
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name='questions',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='questiongroup',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='questions',
            name='deleted_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='forms',
            name='status',
            field=models.IntegerField(choices=[(1, 'draft'), (2, 'published')], default=1),
        ),
        migrations.AddConstraint(
            model_name='questiongroup',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('form', 'name'), name='unique_active_form_question_group'),
        ),
        migrations.AddConstraint(
            model_name='questions',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('form', 'name'), name='unique_active_form_question'),
        ),
    ]
