# Generated by Django 4.0.4 on 2026-07-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0003_organisation_tenant_alter_organisation_name_and_more'),
        ('v1_forms', '0008_forms_deleted_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='forms',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='forms', to='v1_users.tenant'),
        ),
    ]
