# Generated by Django 4.0.4 on 2026-06-03 03:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_forms', '0008_remove_questiongroup_unique_form_question_group_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FormPublishedVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.IntegerField()),
                ('schema', models.JSONField()),
                ('published_at', models.DateTimeField(auto_now_add=True)),
                ('form', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='published_versions', to='v1_forms.forms')),
                ('published_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='published_form_versions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'form_published_version',
                'ordering': ['form', 'version'],
                'unique_together': {('form', 'version')},
            },
        ),
        migrations.AddField(
            model_name='forms',
            name='active_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='active_for_forms', to='v1_forms.formpublishedversion'),
        ),
    ]
