# Generated by Django 4.0.4 on 2026-07-28 08:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0002_tenant_systemuser_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='organisation',
            name='tenant',
            field=models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='organisations', to='v1_users.tenant'),
        ),
        migrations.AlterField(
            model_name='organisation',
            name='name',
            field=models.CharField(max_length=255),
        ),
        migrations.AddConstraint(
            model_name='organisation',
            constraint=models.UniqueConstraint(fields=('tenant', 'name'), name='unique_organisation_name_per_tenant'),
        ),
    ]
