# Generated by Django 4.0.4 on 2026-07-30 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0004_backfill_default_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
