# Generated by Django 4.0.4 on 2026-09-21 05:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0006_unique_email_per_tenant'),
    ]

    operations = [
        migrations.AddField(
            model_name='systemuser',
            name='is_platform_admin',
            field=models.BooleanField(default=False),
        ),
    ]
