# Generated by Django 4.0.4 on 2026-10-01 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0010_tenant_inspection'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='language',
            field=models.CharField(default='en', max_length=10),
        ),
    ]
