# Generated by Django 4.0.4 on 2026-10-06 06:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_users', '0012_schedule_tenant_purge'),
    ]

    operations = [
        migrations.AddField(
            model_name='tenant',
            name='logo',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
