# Generated by Django 4.0.4 on 2026-08-20 04:18

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('v1_users', '0005_systemuser_is_active'),
        ('v1_forms', '0009_forms_tenant'),
        ('v1_visualization', '0001_create_view_data_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Dashboard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('name', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField(default=None, null=True)),
                ('status', models.IntegerField(choices=[(1, 'draft'), (2, 'published')], default=1)),
                ('published_config', models.JSONField(default=None, null=True)),
                ('published_at', models.DateTimeField(default=None, null=True)),
                ('default_filters', models.JSONField(default=dict)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(default=None, null=True)),
                ('created_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='dashboards_created', to=settings.AUTH_USER_MODEL)),
                ('root_form', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='v1_forms.forms')),
                ('tenant', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboards', to='v1_users.tenant')),
            ],
            options={
                'db_table': 'dashboard',
            },
        ),
        migrations.CreateModel(
            name='DashboardWidget',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.IntegerField()),
                ('type', models.IntegerField(choices=[(1, 'kpi'), (2, 'bar'), (3, 'line'), (4, 'pie'), (5, 'table'), (6, 'map'), (7, 'section_title')])),
                ('col_span', models.IntegerField(default=24)),
                ('title', models.CharField(default=None, max_length=255, null=True)),
                ('color', models.CharField(default=None, max_length=32, null=True)),
                ('config', models.JSONField(default=dict)),
                ('dashboard', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='widgets', to='v1_visualization.dashboard')),
                ('form', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='v1_forms.forms')),
                ('question', models.ForeignKey(default=None, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='dashboard_widgets', to='v1_forms.questions')),
            ],
            options={
                'db_table': 'dashboard_widget',
                'ordering': ['dashboard', 'order'],
            },
        ),
        migrations.AddConstraint(
            model_name='dashboard',
            constraint=models.UniqueConstraint(condition=models.Q(('deleted_at__isnull', True)), fields=('tenant', 'slug'), name='unique_active_tenant_dashboard_slug'),
        ),
    ]
