# Generated by Django 4.0.4 on 2026-09-02 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_visualization', '0002_dashboard_dashboardwidget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='is_public',
            field=models.BooleanField(default=False),
        ),
    ]
