# Generated by Django 4.0.4 on 2026-08-27 12:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_visualization', '0002_dashboard_dashboardwidget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='dashboard',
            name='visibility',
            field=models.IntegerField(choices=[(1, 'internal'), (2, 'public')], default=1),
        ),
    ]
