# Generated by Django 4.0.4 on 2026-09-16 05:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('v1_visualization', '0004_dashboard_embed'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dashboardwidget',
            name='type',
            field=models.IntegerField(choices=[(1, 'kpi'), (2, 'bar'), (3, 'line'), (4, 'pie'), (5, 'table'), (6, 'map'), (7, 'section_title'), (8, 'scatter')]),
        ),
    ]
