---
apiVersion: batch/v1
kind: CronJob
metadata:
  name: dws-datapro-jobs
spec:
  schedule: "0 23 * * *"
  startingDeadlineSeconds: 600 # it is ok to start the job 10 minutes late
  concurrencyPolicy: Allow
  failedJobsHistoryLimit: 10
  successfulJobsHistoryLimit: 10
  jobTemplate:
    metadata:
      labels:
        cronjob: dws-datapro-jobs
    spec:
      backoffLimit: 3 # default
      activeDeadlineSeconds: 1800 # Fail job if it takes more than 30 mins
      template:
        metadata:
          labels:
            cronjob: dws-datapro-jobs
        spec:
          containers:
            - name: cloud-sql-proxy
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "1000m"
                  memory: "768Mi"
              # https://cloud.google.com/sql/docs/mysql/connect-kubernetes-engine#run_the_as_a_sidecar
              # It is recommended to use the latest version of the Cloud SQL proxy
              # Make sure to update on a regular schedule!
              image: gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.11.0
              args:
                - "--credentials-file=/secrets/cloudsql/credentials.json"
                - "$(GOOGLE_PROJECT):$(GOOGLE_SQL_COMPUTE_ZONE):$(GOOGLE_SQL_DB_INSTANCE)"

                # When --quitquitquit is set, the admin server adds an endpoint at /quitquitquit. The admin server exits gracefully when it receives a POST request at /quitquitquit.
                # This will be useful for the app to request the cloud-proxy-sql exit for job execution.
                - "--quitquitquit"
                - "--debug-logs"
              securityContext:
                # The default Cloud SQL proxy image runs as the
                # "nonroot" user and group (uid: 65532) by default.
                runAsNonRoot: true
              # https://kubernetes.io/docs/concepts/configuration/manage-resources-containers/
              env:
                - name: GOOGLE_SQL_COMPUTE_ZONE
                  valueFrom:
                    configMapKeyRef:
                      name: dws-datapro
                      key: google-sql-compute-zone
                - name: GOOGLE_SQL_DB_INSTANCE
                  valueFrom:
                    configMapKeyRef:
                      name: dws-datapro
                      key: google-sql-db-instance
                - name: GOOGLE_PROJECT
                  valueFrom:
                    configMapKeyRef:
                      name: dws-datapro
                      key: google-project
              volumeMounts:
                - name: dws-datapro-secrets
                  mountPath: "/secrets/cloudsql/credentials.json"
                  subPath: dws-datapro-service-account.json
                  readOnly: true
            - name: backend
              image: eu.gcr.io/akvo-lumen/dws-datapro/backend:${CI_COMMIT}
              command:
                - /bin/bash
                - -c
                - /app/job.sh;
              env:
                - name: DB_SCHEMA
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: db-schema
                - name: DB_USER
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: db-user
                - name: DB_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: db-password
                - name: DB_HOST
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: db-host
                - name: DJANGO_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: django-secret
                - name: MAILJET_APIKEY
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: mailjet-apikey
                - name: MAILJET_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: mailjet-secret
                - name: EMAIL_FROM
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: email-from
                - name: WEBDOMAIN
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: webdomain
                - name: APP_NAME
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: app-name
                - name: APP_SHORT_NAME
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: app-short-name
                - name: SENTRY_DSN
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: sentry-dsn
                - name: PROD
                  value: "TRUE"
                - name: GOOGLE_APPLICATION_CREDENTIALS
                  value: /secrets/credentials.json
                - name: STORAGE_PATH
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: storage-path
                - name: APK_UPLOAD_SECRET
                  valueFrom:
                    secretKeyRef:
                      name: dws-datapro
                      key: apk-upload-secret
              volumeMounts:
                - name: dws-datapro-secrets
                  mountPath: /secrets/credentials.json
                  subPath: dws-datapro-service-account.json
                  readOnly: true
                - name: nfs-pvc
                  mountPath: "/app/storage"
              resources:
                requests:
                  cpu: "100m"
                  memory: "256Mi"
                limits:
                  cpu: "1000m"
                  memory: "1024Mi"
          volumes:
            - name: dws-datapro-secrets
              secret:
                secretName: dws-datapro
            - name: nfs-pvc
              persistentVolumeClaim:
                claimName: dws-datapro
          restartPolicy: Never
