kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: dws-datapro
spec:
  storageClassName: managed-nfs-storage
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi