# Generated by Django 4.0.4 on 2026-06-03 03:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('v1_forms', '0007_question_model_alignment'),
        ('v1_data', '0003_add_visualization_indexes'),
    ]

    operations = [
        migrations.AddField(
            model_name='formdata',
            name='published_version',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='form_data', to='v1_forms.formpublishedversion'),
        ),
    ]
