import { StyleSheet } from 'react-native';

const getStyles = (theme) =>
  StyleSheet.create({
    formContainer: {
      flex: 1,
    },
    questionGroupContainer: {
      marginBottom: 20,
    },
    fieldGroupHeader: {
      borderColor: 'transparent',
      borderTopWidth: 0,
      borderBottomWidth: 0,
      display: 'flex',
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      minHeight: 48,
      backgroundColor: theme.bg.surfaceTertiary,
      borderRadius: 12,
      marginHorizontal: 10,
      marginBottom: 4,
    },
    fieldGroupName: {
      paddingLeft: 16,
      fontWeight: '700',
      fontSize: 16,
      color: theme.text.primary,
    },
    fieldGroupDescContainer: {
      backgroundColor: theme.bg.surfaceTertiary,
    },
    fieldGroupDescription: {
      fontSize: 14,
      color: theme.text.secondary,
    },
    fieldGroupCopy: {
      paddingVertical: 12,
      paddingHorizontal: 16,
      backgroundColor: 'transparent',
      borderWidth: 0,
      height: '100%',
    },
    questionContainer: {
      paddingHorizontal: 10,
      paddingVertical: 8,
    },
    validationErrorText: {
      paddingHorizontal: 10,
      marginTop: 4,
      color: theme.status.error,
      fontStyle: 'italic',
    },
    fieldLabelContainer: {
      flex: 1,
      flexDirection: 'row',
    },
    fieldRequiredIcon: {
      color: theme.status.error,
      paddingLeft: 10,
    },
    fieldLabel: {
      display: 'flex',
      flexDirection: 'column',
      paddingHorizontal: 10,
      marginBottom: 8,
      fontWeight: '700',
      fontSize: 16,
      color: theme.text.primary,
    },
    inputFieldContainer: {
      paddingHorizontal: 16,
      paddingVertical: 4,
      borderColor: 'transparent',
      borderWidth: 0,
      borderRadius: 12,
      borderBottomWidth: 0,
      backgroundColor: theme.input.bg,
      minHeight: 52,
    },
    inputFieldDisabled: {
      backgroundColor: theme.bg.surfaceTertiary,
      opacity: 0.5,
    },
    inputFieldError: {
      borderColor: theme.status.error,
      borderWidth: 1.5,
      borderBottomWidth: 1.5,
    },
    textAreaContainer: {
      paddingHorizontal: 16,
      borderColor: 'transparent',
      borderWidth: 0,
      borderRadius: 12,
      borderBottomWidth: 0,
      minHeight: 120,
      alignItems: 'flex-start',
      paddingTop: 14,
      backgroundColor: theme.input.bg,
    },
    radioFieldContainer: {
      backgroundColor: 'transparent',
      paddingVertical: 5,
      marginBottom: 0,
    },
    autoFieldContainer: {
      paddingHorizontal: 16,
      paddingVertical: 4,
      borderColor: 'transparent',
      borderWidth: 0,
      borderRadius: 12,
      borderBottomWidth: 0,
      backgroundColor: theme.bg.surfaceChip,
      minHeight: 52,
    },
    radioFieldText: {
      fontWeight: 'normal',
    },
    optionContainer: {
      marginBottom: 4,
    },
    optionSelectedList: {
      backgroundColor: theme.bg.surfaceChip,
      padding: 10,
      marginLeft: 10,
      marginTop: 5,
      borderRadius: 12,
      borderWidth: 0,
    },
    multipleOptionContainer: {
      marginBottom: 4,
    },
    dropdownField: {
      marginHorizontal: 10,
      paddingHorizontal: 16,
      paddingVertical: 14,
      borderColor: 'transparent',
      borderWidth: 0,
      borderRadius: 12,
      backgroundColor: theme.input.bg,
      minHeight: 52,
    },
    dropdownFieldDisabled: {
      backgroundColor: theme.bg.surfaceTertiary,
      opacity: 0.5,
    },
    dropdownSelectedList: {
      marginLeft: 10,
      marginRight: 0,
    },
    formNavigationButton: {
      borderTopColor: theme.border.listDivider,
      borderTopWidth: StyleSheet.hairlineWidth,
      borderBottomWidth: 0,
    },
    formNavigationIcon: {
      paddingTop: 9,
      paddingBottom: 10,
    },
    formNavigationIconSubmit: {
      marginTop: -20,
      marginBottom: -20,
      paddingTop: 9,
      paddingBottom: 10,
      paddingRight: 15,
      marginRight: 0,
      marginLeft: 0,
    },
    formNavigationTitle: {
      paddingTop: 9,
      paddingBottom: 10,
      color: theme.text.secondary,
      fontWeight: 'normal',
      fontSize: 14,
      marginRight: -10,
      marginLeft: -10,
    },
    formNavigationSubmit: {
      paddingTop: 12,
      paddingBottom: 13,
      paddingRight: 10,
      color: theme.buttonPrimary.text,
      fontWeight: 'normal',
      fontSize: 14,
    },
    formNavigationGroupCount: {
      paddingTop: 13,
      paddingBottom: 10,
      color: theme.text.secondary,
      fontWeight: 'normal',
      fontSize: 14,
      marginRight: -10,
      marginLeft: -10,
    },
    formNavigationBgLight: {
      backgroundColor: theme.bg.surfaceTertiary,
    },
    formNavigationBgPrimary: {
      backgroundColor: theme.buttonPrimary.bg,
    },
    inputGeoContainer: {
      paddingHorizontal: 16,
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
      marginBottom: 18,
    },
    questionGroupListContainer: {
      paddingTop: 24,
      flex: 1,
      width: '100%',
    },
    divider: {
      paddingHorizontal: 20,
      marginVertical: 7,
    },
    questionGroupListFormTitle: {
      paddingHorizontal: 20,
      fontSize: 20,
      fontWeight: 'bold',
      marginBottom: 4,
      color: theme.text.primary,
    },
    questionGroupListDataPointName: {
      paddingHorizontal: 20,
      fontSize: 16,
      marginBottom: 4,
      color: theme.text.secondary,
    },
    questionGroupListItemWrapper: {
      display: 'flex',
      flexDirection: 'row',
      width: '100%',
      paddingVertical: 10,
      alignItems: 'center',
      paddingHorizontal: 14,
      borderRadius: 12,
    },
    questionGroupListItemActive: {
      backgroundColor: theme.bg.surfaceTranslucent,
    },
    questionGroupListItemIcon: {
      paddingHorizontal: 10,
      paddingVertical: 5,
    },
    questionGroupListItemName: {
      marginLeft: 10,
      color: theme.text.primary,
    },
    questionGroupListItemNameActive: {
      fontWeight: 'bold',
    },
    cascadeContainer: {
      display: 'flex',
      flexDirection: 'column',
      gap: 10,
      marginBottom: 4,
    },
    cascadeValues: {
      opacity: 0,
      marginBottom: -16,
    },
    polygonWarningText: {
      color: theme.status.warning,
      fontSize: 13,
    },
    geoButtonGroup: {
      display: 'flex',
      flexDirection: 'column',
      gap: 8,
    },
    errorText: {
      color: theme.status.error,
      fontStyle: 'italic',
    },
    repeatSectionContainer: {
      marginVertical: 10,
    },
    repeatDivider: {
      backgroundColor: theme.border.listDivider,
      height: 1.5,
      marginVertical: 10,
    },
    repeatSectionHeader: {
      flexDirection: 'row',
      justifyContent: 'space-between',
      alignItems: 'center',
      paddingHorizontal: 14,
      paddingVertical: 10,
      backgroundColor: theme.bg.surfaceTertiary,
      borderRadius: 12,
      marginBottom: 10,
    },
    repeatSectionTitle: {
      fontSize: 14,
      fontWeight: 'bold',
      color: theme.text.secondary,
    },
    repeatSectionRemove: {
      padding: 5,
    },
  });

export default getStyles;
